"""add_expires_at_to_blood_requests

Revision ID: 12fb7ac5e8b2
Revises: e285040fd87d
Create Date: 2026-08-27 15:26:14.986288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12fb7ac5e8b2'
down_revision: Union[str, None] = 'e285040fd87d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blood_requests', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.create_index('ix_blood_requests_expires_at', 'blood_requests', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_blood_requests_expires_at', table_name='blood_requests')
    op.drop_column('blood_requests', 'expires_at')
    # ### end Alembic commands ###
